# Generated by Django 4.2.5 on 2023-10-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
    ]
