# Generated by Django 4.2.5 on 2023-10-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gastos', '0002_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50, verbose_name='Concepto')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gastos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gastos.banco')),
                ('id_concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.concepto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gastos.tipo')),
            ],
        ),
    ]
