# Generated by Django 4.2.5 on 2023-10-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(blank=True, verbose_name='Fecha'),
        ),
    ]
