# Generated by Django 4.2.5 on 2023-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto'),
        ),
    ]
